HomeworkCentre/Homework/urls.py
from . import homework_views
from .import homework_solution_views
from django.urls import path

urlpatterns = [
    path('', homework_views.HomeworkList.as_view(), name='homeworks'),
    path('<int:class_id>', homework_views.HomeworkList.as_view(), name='homeworks_for_class'),
    path('create/', homework_views.HomeworkFormView.as_view(),
         name='create_homework'),
    path('solution/create/<int:pk>', homework_solution_views.HomeworkSolutionCreateView.as_view(),
         name='create_solution'),
    path('solution/', homework_solution_views.HomeworkSolutionListView.as_view(),
         name='solutions'),
    path('<int:id>/solution', homework_solution_views.HomeworkSolutionListView.as_view(),
         name='solutions_to_homework'),
    path('solution/<int:pk>/rate', homework_solution_views.HomeworkSolutionRatingCreateView.as_view(),
         name='rating_create'),
    path('rating/', homework_solution_views.HomeworkSolutionRatingListView.as_view(),
         name='ratings'),
    path('<int:homework_id>/rating', homework_solution_views.HomeworkSolutionRatingListView.as_view(),
         name='ratings_to_homework'),
    path('rating/<int:pk>', homework_solution_views.HomeworkSolutionRatingDetailView.as_view(),
         name='rating'),

]

app_name = 'Homework'

HomeworkCentre/HomeworkCentre/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homework/', include('Homework.urls', namespace='homework')),
    path('', include('User.urls', namespace='user')),
    path('user/', include('User.urls', namespace='user')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HomeworkCentre/User/urls.py
from . import views
from django.urls import path
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('classes/', views.StudentClassListView.as_view(), name='classes'),
    path('classes/<int:class_id>/members', views.StudentClassMembersListView.as_view(), name='class_members'),
    path('classes/available', views.StudentClassListView.as_view(available=True), name='classes_available'),
    path('classes/create', views.CreateStudentsClass.as_view(), name='class_create'),
    path('classes/join/<int:pk>', views.join_to_class, name='class_join'),
    path('register/', views.RegisterView.as_view(), name='user_register'),
    path('login/', views.CustomLoginView.as_view(), name='user_login'),
    path('logout/', LogoutView.as_view(next_page='user:user_login'), name='user_logout'),
]

app_name = 'User'

HomeworkCentre/Homework/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from User.models import CustomUser, StudentsClass
from multiselectfield import MultiSelectField

# Create your models here.


class Homework(models.Model):
    # NEED REFACTOR
    AVAILABLE_FORMATS = (('pdf', 'pdf'),
                         ('doc', 'doc'),
                         ('docx', 'docx'),
                         ('txt', 'txt'),
                         ('py', 'py'),
                         ('cpp', 'cpp'),
                         ('mp3', 'mp3'),
                         ('jpg', 'jpg'),
                         ('png', 'png'),
                         ('zip', 'zip'),
                         ('rar', 'rar'),
                         ('tar.gz', 'tar.gz'))
    title = models.CharField(blank=False, null=False,
                             unique=True, max_length=250)
    description = models.TextField(blank=True, null=True, max_length=500)
    available_formats = MultiSelectField(
        choices=AVAILABLE_FORMATS, null=False, blank=False)
    deadline = models.DateTimeField(
        auto_now_add=False, blank=False, null=False)
    teacher = models.ForeignKey(CustomUser, on_delete=models.CASCADE, limit_choices_to={
                                'groups__name': "Teachers"}, related_name='teacher')
    students = models.ManyToManyField(
        StudentsClass, related_name='students')

    def __str__(self):
        return f'{self.title}'


class HomeworkSolution(models.Model):
    homework = models.ForeignKey(
        Homework, on_delete=models.CASCADE, related_name='homework')
    homework_file = models.FileField(
        upload_to=f'homework_solutions/', null=False, blank=True, )
    description = models.TextField(blank=True, null=True, max_length=320)
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE,  limit_choices_to={
        'groups__name': "Students"}, related_name='student')
    date_added = models.DateTimeField(auto_now=True)

    def __str__(self):
        homework_name = self.homework.title
        return f'{homework_name} - {self.student}'


class HomeworkSolutionRating(models.Model):
    rating = models.PositiveIntegerField(null=False, blank=False, validators=[
        MinValueValidator(1),
        MaxValueValidator(5)
    ])

    feedback = models.CharField(null=True, blank=True, max_length=300)
    solution = models.OneToOneField(
        HomeworkSolution, on_delete=models.CASCADE, related_name='solution_rated')
    rated_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, limit_choices_to={
        'groups__name': "Teachers"}, related_name='rated_by'
    )

    date_added = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f'{self.solution} | {self.rated_by} | {self.date_added}'


HomeworkCentre/templates/user_templates/add_students_class.html
{% extends 'index.html' %}
{%load materializecss %}
{% load static %}

{% block title %}DODAJ KLASE {% endblock title %}
{% block css %}

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css"
    integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
<!-- <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}"> -->

{% endblock css %}

{% block javascript %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js"
    integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

<script>
    $(document).ready(function () {

        // Initialize materialize data picker
        $('.datepicker').datepicker({
            'format': 'yyyy-mm-dd',
            'i18n': {
                'months': ["Styczeń", "Luty", "Marzec", "Kwiecień", "Maj", "Czerwiec",
                    "Lipiec", "Sierpień", "Wrzesień", "Październik", "Listopad", "Grudzień"],
                'monthsShort': ["Sty", "Lut", "Mar", "Kwi", "Maj", "Cze", "Lip", "Sie", "Wrz", "Paź", "Lis", "Gru"],
                'weekdays': ["Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota", "Niedziela"],
                'weekdaysShort': ["Pon", "Wto", "Śro", "Czw", "Pią", "Sob", "Nie"],
                'weekdaysAbbrev': ["P", "W", "Ś", "C", "Pt", "S", "N"]
            }
        });
        $('.timepicker').timepicker({
            'twelveHour': false
        });
        $('select').formSelect();

    });
</script>
{% endblock javascript %}

{%block content %}
<style>
    .card {
        /* -webkit-border-radius: 70px;
        -moz-border-radius: 70px;
        border-radius: 70px; */
        padding: 10px;
    }

    .waves-effect {
        width: 100%;
    }
</style>
<div class="container ">
    <h1>DODAJ KLASĘ</h1>
    <div class="card">
        <form action="" method="POST">
            {% csrf_token %}
            {{form|materializecss}}
            <button type="submit" class="waves-effect green btn">DODAJ</button>
        </form>
    </div>
</div>
{%endblock content %}

HomeworkCentre/templates/user_templates/available_classes.html
{% extends 'index.html' %}
{% block title %}KLASY{% endblock title %}

{% block content %}
<div class="container">
<h1>Klasy, do których możesz dołączyć</h1>
<div class="row">
    {% for class in class_list %}
    <div class="col s6 m4">
        <div class="card center">
            <div class="card-image">
                <i class="large material-icons grey-text text-darken-3">school</i>

                <a class="btn-floating halfway-fab waves-effect waves-light green pulse"
                    href="{% url 'User:class_join' class.id %}"><i class="material-icons">add</i></a>
            </div>
            <div class="card-content center">
                <p>{{class.name}}</p>
                <cite>
                <p>{{class.description}}</p>
                </cite>
                <p>{{class.owner}}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
</div>
{% endblock content %}

HomeworkCentre/templates/user_templates/login.html
{% extends 'index.html' %}
{% load materializecss %}
{%block title %}
LOGOWANIE
{% endblock title %}


{% block javascript %}



{% endblock javascript %}

{% block menu %}
{% endblock menu %}
{%block content %}

<div class="row">
    <div class="col s12 m4 offset-m4">
        <div class="card">
            <div class="card-action light-blue darken-4 hoverable white-text">
                <h3 class="center">LOGOWANIE</h3>
            </div>
            <div class="card-content">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <div class="form-field s12 center">
                        <a href="{% url 'user:user_register' %}" class="black-text center">Nie masz konta? Zarejestruj się</a>
                    </div>
                    <div class="form-field s12">
                        <button class="btn-large waves-effect light-blue darken-4" style="width:100%;"
                            type="submit">ZALOGUJ</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

HomeworkCentre/templates/user_templates/register.html
{% extends 'index.html' %}
{% load materializecss %}
{%block title %}
ZAREJESTRUJ
{% endblock title %}


{% block javascript %}


<script>
    $(document).ready(function () {

        // Initialize materialize data picker
        $('select').formSelect();

    });
</script>
{% endblock javascript %}

{% block menu %}
{% endblock menu %}
{%block content %}
<!-- <div class="container ">

    <h1>REJESTRACJA</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{form|materializecss}}
        <button type="submit" class="waves-effect waves-light btn">DODAJ</button>
    </form>
</div> -->

<div class="row">
    <div class="col s12 m4 offset-m4">
        <div class="card">
            <div class="card-action light-blue darken-4 hoverable white-text">
                <h3 class="center">REJESTRACJA</h3>
            </div>
            <div class="card-content">
                <form action="" method="POST">
                    {% csrf_token %} 
                <div class="form-field">
                    {{form.username|materializecss}}
                </div>
                <div class="form-field">
                    {{form.email|materializecss}}
                </div>
                <div class="form-field">
                    {{form.first_name|materializecss}}
                </div>
                <div class="form-field">
                    {{form.last_name|materializecss}}
                </div>
                <div class="form-field">
                    {{form.password1|materializecss}}
                </div>
                <div class="form-field">
                    {{form.password2|materializecss}}
                </div>
                <div class="form-field">
                    {{form.role|materializecss}}
                </div>
                <div class="form-field s12">
                   <button class="btn-large waves-effect light-blue darken-4" style="width:100%;" type="submit">ZAREJESTRUJ</button>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

HomeworkCentre/templates/user_templates/student_classes.html
{% extends 'index.html' %}
{% block title %}KLASY{% endblock title %}

{% block content %}
<style>
    .card.white.hoverable {
        height: 300px;
    }
</style>
<div class="container">
    <h1>Twoje klasy</h1>
    <div class="row">
        {% for class in class_list %}
        <div class="col s4 center ">
            <div class="small card white hoverable ">
                <div class="card-image">
                    <i class="large material-icons grey-text text-darken-3">school</i>

                </div>
                <div class="card-content center">
                    <span class="card-title ">{{class.name}}</span>
                    <p>{{class.description}}</p>
                    <p>{{class.owner}}</p>
                </div>
                <div class="card-action">
                    <a href="{% url 'homework:homeworks_for_class' class.id %}" class="green-text">Zadania</a>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="col s4 center ">
            <div class="small card white hoverable ">
                <div class="card-image">
                    <i class="large material-icons grey-text text-darken-3">school</i>
        
                </div>
                <div class="card-content center">
                    <span class="card-title"><a href="{% url 'user:classes_available' %}"><i class="medium material-icons green-text ">add</i></a></span>
                    <p>Dołącz do nowej klasy</p>
                    <p>{{class.owner}}</p>
                </div>
            
            </div>
        </div>
    </div>
</div>
{% endblock content %}

HomeworkCentre/templates/user_templates/student_main.html
{% extends 'index.html' %}

{% block title %}GŁÓWNA{% endblock title %}

{% block content %}
<style>
   .card-panel {
      height: 250px;
   }

   /* td {
      max-width: 33.33%;
   } */

   /* a {
      color: black;
   } */
</style>
<div class="container center">
   <div class="row">
      <div class="col s12 m6">
         <div class="card">
            <div class="card-title">
               OSTATNIE OCENY
            </div>
            <div class="card-action">
               <table class="striped">
                  <thead>
                     <tr>
                        <th>Zadanie</th>
                        <th>Ocena</th>
                        <th>Data</th>
                        <th>Szczegóły</th>
                     </tr>
                  </thead>

                  <tbody>
                     {% for rating in rating_list %}
                     <tr>
                        <td>{{rating.solution.homework}}</td>
                        <td>{{rating.rating}}</td>
                        <td>{{rating.date_added|date:'d-m-Y H:i'}}</td>
                        <td><a class="waves-effect green btn-small" href="{% url 'homework:rating' rating.id %}"><i
                                 class="material-icons center">info_outline</i></a></td>
                     </tr>
                     {% endfor %}

                  </tbody>
               </table>
            </div>
         </div>
      </div>

      <div class="col s12 m6">
         <div class="card">
            <div class="card-title">
               OSTATNIE ZADANIA
            </div>
            <div class="card-action">
               <table class="striped">
                  <thead>
                     <tr>
                        <th>Zadanie</th>
                        <th>Kto</th>
                        <th>Termin oddania</th>
                        <th>Oddaj</th>
                     </tr>
                  </thead>

                  <tbody>
                     {% for homework in homework_list %}
                     <tr>
                        <td>{{homework.title}}</td>
                        <td>{{homework.teacher}}</td>
                        <td>{{homework.deadline|date:'d-m-Y H:i'}}</td>
                        <td><a class="waves-effect green btn-small"
                              href="{% url 'homework:create_solution' homework.id %}"><i
                                 class="material-icons center">add</i></a></td>
                     </tr>
                     {% endfor %}


                  </tbody>
               </table>
            </div>
         </div>
      </div>
   </div>

   <div class="row">
      <div class="col s12 m4">
         <a href="{% url 'user:classes' %}" class="grey-text text-darken-3">
            <div class="card-panel hoverable">
               <i class="material-icons large grey-text text-darken-3">school</i>
               <h4>Klasy</h4>
               <p>Wyświetl wszystkie klasy, do których należysz</p>
            </div>
         </a>
      </div>

      <div class="col s12 m4">
         <a href="{% url 'homework:ratings' %}" class="grey-text text-darken-3">
            <div class="card-panel hoverable">
               <i class="material-icons large grey-text text-darken-3">stars</i>
               <h4>Oceny</h4>
               <p>Wyświetl wszystkie Twoje oceny</p>
            </div>
         </a>
      </div>

      <div class="col s12 m4">
         <a href="{% url 'homework:homeworks' %}" class="grey-text text-darken-3">
            <div class="card-panel hoverable">
               <i class="material-icons large grey-text text-darken-3">event</i>
               <h4>Zadania</h4>
               <p>Wyświetl zadania, na które możesz jeszcze udzielić odpowiedzi</p>
            </div>
      </div>
      </a>
   </div>

</div>

{% endblock content %}

HomeworkCentre/templates/user_templates/teacher_class_members.html
{% extends 'index.html' %}

{% block title %}ZADANIA{% endblock title %}

{% block content %}

<div class="container">
    <table class="responsive-table highlight">
        <thead>
            <tr>
                <th>Imię</th>
                <th>Nazwisko</th>
            </tr>
        </thead>

        <tbody>
            {% for member in members|dictsort:"last_name"|dictsortreversed:"first_name" %}
            <tr>
                <td>{{member.first_name}}</td>
                <td>{{member.last_name}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}

HomeworkCentre/templates/user_templates/teacher_classes.html
{% extends 'index.html' %}
{% block title %}KLASY{% endblock title %}

{% block content %}
<style>
    .card.white.hoverable {
        height: 300px;
    }
</style>
<div class="container">
    <h1>Twoje klasy</h1>
    <div class="row">
        {% for class in class_list %}
        <div class="col s4 center ">
            <a href="{% url 'user:class_members' class.id %}" class="black-text">
            <div class="small card white hoverable ">
                <div class="card-image">
                    <i class="large material-icons grey-text text-darken-3">school</i>

                </div>
                <div class="card-content center">
                    <span class="card-title ">{{class.name}}</span>
                    <p>{{class.description}}</p>
                    <p>{{class.owner}}</p>
                </div>
                <div class="card-action">
                    <a href="{% url 'homework:homeworks_for_class' class.id %}" class="green-text">Zadania</a>
                </div>
            </div>
            </a>
        </div>
        {% endfor %}
        <div class="col s4 center ">
            <div class="small card white hoverable ">
                <div class="card-image">
                    <i class="large material-icons grey-text text-darken-3">school</i>
        
                </div>
                <div class="card-content center">
                    <span class="card-title"><a href="{% url 'user:class_create' %}"><i class="medium material-icons green-text ">add</i></a></span>
                    <p>Utwórz nową klasę</p>
                    <p>{{class.owner}}</p>
                </div>
            
            </div>
        </div>
    </div>
</div>
{% endblock content %}

HomeworkCentre/templates/user_templates/teacher_main.html
{% extends 'index.html' %}

{% block title %}GŁÓWNA{% endblock title %}

{% block content %}
<style>
   .card-panel {
      height: 250px;
   }

   /* td {
   max-width: 33.33%;
} */

   /* a {
   color: black;
} */

   table {
      table-layout: fixed;
   }

   /* td {
      width: 33.33%;
   } */
</style>
<div class="container center">
   <div class="row">
      <div class="col s12 m4">
         <div class="card">
            <div class="card-title">
               OSTATNIE ODPOWIEDZI
            </div>
            <div class="card-action">
               <table class="striped">
                  <thead>
                     <tr>
                        <th>Zadanie</th>
                        <th>Uczeń</th>
                        <!-- <th>Data</th> -->
                        <th>Oceń</th>
                     </tr>
                  </thead>

                  <tbody>
                     {% for solution in solution_list %}
                     <tr>
                        <td><span class="truncate">{{solution.homework.title}}</span></td>
                        <td>{{solution.student}}</td>
                        <!-- <td>{{solution.date_added|date:'d-m-Y H:i'}}</td> -->
                        <td><a class="waves-effect green btn-small"
                              href="{% url 'homework:rating_create' solution.id %}"><i
                                 class="material-icons center">create</i></a></td>
                     </tr>
                     {% endfor %}


                  </tbody>
               </table>
            </div>
         </div>
      </div>

      <div class="col s12 m4">
         <div class="card">
            <div class="card-title">
               OSTATNIE OCENY
            </div>
            <div class="card-action">
               <table class="striped responsive">
                  <thead>
                     <tr>
                        <th>Zadanie</th>
                        <th>Uczeń</th>
                        <th>Ocena</th>
                        <th>Szczegóły</th>
                     </tr>
                  </thead>

                  <tbody>
                     {% for rating in rating_list %}
                     <tr>
                        <td> <span class="truncate">{{rating.solution.homework}}</span></td>
                        <td>{{rating.solution.student}}</td>
                        <td>{{rating.rating}}</td>
                        <td><a class="waves-effect green btn-small" href="{%url 'homework:rating' rating.id %}"><i
                                 class="material-icons center">info_outline</i></a></td>
                     </tr>
                     {% endfor %}


                  </tbody>
               </table>
            </div>
         </div>
      </div>

      <div class="col s12 m4">
         <div class="card">
            <div class="card-title">
               OSTATNIE ZADANIA
            </div>
            <div class="card-action">
               <table class="striped">
                  <thead>
                     <tr>
                        <th>Zadanie</th>
                        <th>Termin</th>
                        <th>Odp.</th>
                        <th>Oceny</th>
                     </tr>
                  </thead>

                  <tbody>
                     {% for homework in homework_list %}
                     <tr>
                        <td><span class="truncate">{{homework.title}}</span></td>
                        <td>{{homework.deadline|date:'d-m-Y H:i'}}</td>
                        <td><a class="waves-effect green btn-small"
                              href="{% url 'homework:solutions_to_homework' homework.id %}"><i
                                 class="material-icons center">library_books</i></a></td>
                        <td><a class="waves-effect green btn-small"
                              href="{% url 'homework:ratings_to_homework' homework.id %}"><i
                                 class="material-icons center">check</i></a></td>
                     </tr>
                     {% endfor %}


                  </tbody>
               </table>
            </div>
         </div>
      </div>
   </div>

   <div class="row">
      <div class="col s12 m4">
         <a href="{% url 'user:classes' %}" class="grey-text text-darken-3">
            <div class="card-panel hoverable">
               <i class="material-icons large grey-text text-darken-3">school</i>
               <h4>Klasy</h4>
               <p>Wyświetl wszystkie klasy, które należą do Ciebie</p>
            </div>
         </a>
      </div>

      <div class="col s12 m4">
         <a href="{% url 'homework:solutions' %}" class="grey-text text-darken-3">
            <div class="card-panel hoverable">
               <i class="material-icons large grey-text text-darken-3">task</i>
               <h4>Odpowiedzi</h4>
               <p>Wyświetl wszystkie nieocenione odpowiedzi do Twoich zadań</p>
            </div>
         </a>
      </div>

      <div class="col s12 m4">
         <a href="{% url 'homework:homeworks' %}" class="grey-text text-darken-3">
            <div class="card-panel hoverable">
               <i class="material-icons large grey-text text-darken-3">event</i>
               <h4>Zadania</h4>
               <p>Wyświetl zadania, których jesteś autorem</p>
            </div>
      </div>
      </a>
   </div>

</div>

{% endblock content %}