HomeworkCentre/Homework/urls.py
from . import homework_views
from .import homework_solution_views
from django.urls import path

urlpatterns = [
    path('', homework_views.HomeworkList.as_view(), name='homeworks'),
    path('<int:class_id>', homework_views.HomeworkList.as_view(), name='homeworks_for_class'),
    path('create/', homework_views.HomeworkFormView.as_view(),
         name='create_homework'),
    path('solution/create/<int:pk>', homework_solution_views.HomeworkSolutionCreateView.as_view(),
         name='create_solution'),
    path('solution/', homework_solution_views.HomeworkSolutionListView.as_view(),
         name='solutions'),
    path('<int:id>/solution', homework_solution_views.HomeworkSolutionListView.as_view(),
         name='solutions_to_homework'),
    path('solution/<int:pk>/rate', homework_solution_views.HomeworkSolutionRatingCreateView.as_view(),
         name='rating_create'),
    path('rating/', homework_solution_views.HomeworkSolutionRatingListView.as_view(),
         name='ratings'),
    path('<int:homework_id>/rating', homework_solution_views.HomeworkSolutionRatingListView.as_view(),
         name='ratings_to_homework'),
    path('rating/<int:pk>', homework_solution_views.HomeworkSolutionRatingDetailView.as_view(),
         name='rating'),

]

app_name = 'Homework'

HomeworkCentre/HomeworkCentre/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homework/', include('Homework.urls', namespace='homework')),
    path('', include('User.urls', namespace='user')),
    path('user/', include('User.urls', namespace='user')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HomeworkCentre/User/urls.py
from . import views
from django.urls import path
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('classes/', views.StudentClassListView.as_view(), name='classes'),
    path('classes/<int:class_id>/members', views.StudentClassMembersListView.as_view(), name='class_members'),
    path('classes/available', views.StudentClassListView.as_view(available=True), name='classes_available'),
    path('classes/create', views.CreateStudentsClass.as_view(), name='class_create'),
    path('classes/join/<int:pk>', views.join_to_class, name='class_join'),
    path('register/', views.RegisterView.as_view(), name='user_register'),
    path('login/', views.CustomLoginView.as_view(), name='user_login'),
    path('logout/', LogoutView.as_view(next_page='user:user_login'), name='user_logout'),
]

app_name = 'User'

HomeworkCentre/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
    <link rel="icon" type="image/png" href="https://example.com/favicon.png" />
    <title>{% block title %} {% endblock %}</title>

    {%block css%}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css"
        integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js"
        integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>
        
    {%endblock%}

</head>

<body>
    {%block javascript %}
    {%endblock%}

    {% block menu %}

     {% if request.user.groups.all.0.name == 'Teachers' %}
        {% include 'teacher_menu.html' %}
    {% else %}
     {% include 'student_menu.html' %}
    {% endif %}

    {% endblock %}  

    

    {%block content %}
    {%endblock %}
</body>

</html>

HomeworkCentre/templates/student_menu.html
<script>
    $(document).ready(function () {
        $('.sidenav').sidenav();
        $(".dropdown-trigger").dropdown();
    });


</script>


<div class="navbar-fixed">

    <nav>
        <div class="nav-wrapper light-blue darken-4">
            <a href="{% url 'user:home' %}" class="brand-logo"><i
                    class="material-icons left">business_center</i>HomeworkCentre</a>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                <li><a href="{% url 'homework:homeworks' %}"><i class="material-icons left">event</i>ZADANIA</a></li>
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown1" href="badges.html"><i
                            class="material-icons left">school</i>KLASY</a></li>
                <li><a href="{% url 'homework:ratings' %}"><i class="material-icons left">grade</i>OCENY</a></li>
                <li><a href="{% url 'user:user_logout' %}"><i class="material-icons left">close</i>Wyloguj</a></li>
            </ul>
        </div>
    </nav>
</div>

<ul class="sidenav" id="mobile-demo">
    <li><a href="{% url 'homework:homeworks' %}">Zadania</a></li>
    <li><a href="{% url 'user:classes' %}">Klasy</a></li>
    <li><a href="{% url 'homework:ratings' %}">Oceny</a></li>
</ul>

<ul id="dropdown1" class="dropdown-content">
    <li><a href="{% url 'user:classes' %}">Twoje</a></li>
    <li class="divider"></li>
    <li><a href="{% url 'user:classes_available' %}">Dołącz</a></li>

</ul>

HomeworkCentre/templates/teacher_menu.html
<script>
    $(document).ready(function () {
        $('.sidenav').sidenav();
        $(".dropdown-trigger").dropdown();
    });


</script>


<div class="navbar-fixed">

    <nav>
        <div class="nav-wrapper light-blue darken-4">
            <a href="{% url 'user:home' %}" class="brand-logo"><i
                    class="material-icons left">business_center</i>HomeworkCentre</a>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown2" href="badges.html"><i
                            class="material-icons left">event</i>ZADANIA</a></li>
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown1" href="badges.html"><i
                            class="material-icons left">school</i>KLASY</a></li>
                <li><a href="{% url 'homework:ratings' %}"><i class="material-icons left">grade</i>OCENY</a></li>
                <li><a href="{% url 'user:user_logout' %}"><i class="material-icons left">close</i>Wyloguj</a></li>
            </ul>
        </div>
    </nav>
</div>

<ul class="sidenav" id="mobile-demo">
    <li><a href="{% url 'homework:homeworks' %}">Zadania</a></li>
    <li><a href="{% url 'user:classes' %}">Klasy</a></li>
    <li><a href="{% url 'homework:ratings' %}">Oceny</a></li>
</ul>

<ul id="dropdown1" class="dropdown-content">
    <li><a href="{% url 'user:classes' %}">Twoje</a></li>
    <li class="divider"></li>
    <li><a href="{% url 'user:class_create' %}">Utwórz nową</a></li>

</ul>

<ul id="dropdown2" class="dropdown-content">
    <li><a href="{% url 'homework:homeworks' %}">Wszystkie</a></li>
    <li class="divider"></li>
    <li><a href="{% url 'homework:create_homework' %}">Utwórz nowe</a></li>

</ul>