HomeworkCentre/Homework/urls.py
from . import homework_views
from .import homework_solution_views
from django.urls import path

urlpatterns = [
    path('', homework_views.HomeworkList.as_view(), name='homeworks'),
    path('<int:class_id>', homework_views.HomeworkList.as_view(), name='homeworks_for_class'),
    path('create/', homework_views.HomeworkFormView.as_view(),
         name='create_homework'),
    path('solution/create/<int:pk>', homework_solution_views.HomeworkSolutionCreateView.as_view(),
         name='create_solution'),
    path('solution/', homework_solution_views.HomeworkSolutionListView.as_view(),
         name='solutions'),
    path('<int:id>/solution', homework_solution_views.HomeworkSolutionListView.as_view(),
         name='solutions_to_homework'),
    path('solution/<int:pk>/rate', homework_solution_views.HomeworkSolutionRatingCreateView.as_view(),
         name='rating_create'),
    path('rating/', homework_solution_views.HomeworkSolutionRatingListView.as_view(),
         name='ratings'),
    path('<int:homework_id>/rating', homework_solution_views.HomeworkSolutionRatingListView.as_view(),
         name='ratings_to_homework'),
    path('rating/<int:pk>', homework_solution_views.HomeworkSolutionRatingDetailView.as_view(),
         name='rating'),

]

app_name = 'Homework'

HomeworkCentre/HomeworkCentre/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homework/', include('Homework.urls', namespace='homework')),
    path('', include('User.urls', namespace='user')),
    path('user/', include('User.urls', namespace='user')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HomeworkCentre/User/urls.py
from . import views
from django.urls import path
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('classes/', views.StudentClassListView.as_view(), name='classes'),
    path('classes/<int:class_id>/members', views.StudentClassMembersListView.as_view(), name='class_members'),
    path('classes/available', views.StudentClassListView.as_view(available=True), name='classes_available'),
    path('classes/create', views.CreateStudentsClass.as_view(), name='class_create'),
    path('classes/join/<int:pk>', views.join_to_class, name='class_join'),
    path('register/', views.RegisterView.as_view(), name='user_register'),
    path('login/', views.CustomLoginView.as_view(), name='user_login'),
    path('logout/', LogoutView.as_view(next_page='user:user_login'), name='user_logout'),
]

app_name = 'User'

HomeworkCentre/Homework/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from User.models import CustomUser, StudentsClass
from multiselectfield import MultiSelectField

# Create your models here.


class Homework(models.Model):
    # NEED REFACTOR
    AVAILABLE_FORMATS = (('pdf', 'pdf'),
                         ('doc', 'doc'),
                         ('docx', 'docx'),
                         ('txt', 'txt'),
                         ('py', 'py'),
                         ('cpp', 'cpp'),
                         ('mp3', 'mp3'),
                         ('jpg', 'jpg'),
                         ('png', 'png'),
                         ('zip', 'zip'),
                         ('rar', 'rar'),
                         ('tar.gz', 'tar.gz'))
    title = models.CharField(blank=False, null=False,
                             unique=True, max_length=250)
    description = models.TextField(blank=True, null=True, max_length=500)
    available_formats = MultiSelectField(
        choices=AVAILABLE_FORMATS, null=False, blank=False)
    deadline = models.DateTimeField(
        auto_now_add=False, blank=False, null=False)
    teacher = models.ForeignKey(CustomUser, on_delete=models.CASCADE, limit_choices_to={
                                'groups__name': "Teachers"}, related_name='teacher')
    students = models.ManyToManyField(
        StudentsClass, related_name='students')

    def __str__(self):
        return f'{self.title}'


class HomeworkSolution(models.Model):
    homework = models.ForeignKey(
        Homework, on_delete=models.CASCADE, related_name='homework')
    homework_file = models.FileField(
        upload_to=f'homework_solutions/', null=False, blank=True, )
    description = models.TextField(blank=True, null=True, max_length=320)
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE,  limit_choices_to={
        'groups__name': "Students"}, related_name='student')
    date_added = models.DateTimeField(auto_now=True)

    def __str__(self):
        homework_name = self.homework.title
        return f'{homework_name} - {self.student}'


class HomeworkSolutionRating(models.Model):
    rating = models.PositiveIntegerField(null=False, blank=False, validators=[
        MinValueValidator(1),
        MaxValueValidator(5)
    ])

    feedback = models.CharField(null=True, blank=True, max_length=300)
    solution = models.OneToOneField(
        HomeworkSolution, on_delete=models.CASCADE, related_name='solution_rated')
    rated_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, limit_choices_to={
        'groups__name': "Teachers"}, related_name='rated_by'
    )

    date_added = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f'{self.solution} | {self.rated_by} | {self.date_added}'


HomeworkCentre/templates/homework_templates/add_homework.html
{% extends 'index.html' %}

{% load static %}

{% block title %}DODAJ ZADANIE {% endblock title %}
{% block css %}
{%load materializecss %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css"
    integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
<!-- <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}"> -->
{% endblock css %}

{% block javascript %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js"
    integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

<script>
    $(document).ready(function () {

        // Initialize materialize data picker
        $('.datepicker').datepicker({
            'format': 'yyyy-mm-dd',
            'i18n': {
                'months': ["Styczeń", "Luty", "Marzec", "Kwiecień", "Maj", "Czerwiec",
                    "Lipiec", "Sierpień", "Wrzesień", "Październik", "Listopad", "Grudzień"],
                'monthsShort': ["Sty", "Lut", "Mar", "Kwi", "Maj", "Cze", "Lip", "Sie", "Wrz", "Paź", "Lis", "Gru"],
                'weekdays': ["Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota", "Niedziela"],
                'weekdaysShort': ["Pon", "Wto", "Śro", "Czw", "Pią", "Sob", "Nie"],
                'weekdaysAbbrev': ["P", "W", "Ś", "C", "Pt", "S", "N"]
            }
        });
        $('.timepicker').timepicker({
            'twelveHour': false
        });
        $('select').formSelect();

    });
</script>
{% endblock javascript %}

{%block content %}
<style>
    div.card.title {
        -webkit-border-top-left-radius: 85px;
        -moz-border-radius-topleft: 85px;
        border-top-left-radius: 85px;
        padding-left: 30px;
    }

    div.card.main {
        -webkit-border-radius: 50px;
        -moz-border-radius: 50px;
        border-radius: 50px;
        padding-left: 30px;
        padding-top: 10px;
        padding-bottom: 10px;
        color: red;

    }

    div.card {
        border: 1px grey solid;
        
    }

    div.card.date {
        -webkit-border-bottom-right-radius: 85px;
        -moz-border-radius-bottomright: 85px;
        border-bottom-right-radius: 85px;
        padding-left: 30px;
        padding-top: 10px;
        
    }

    .input-field label {
        color: #000;
    }

    div.col.s12 ul label {
        color: black;
    }
</style>

<div class="container">
    <h1>DODAJ ZADANIE</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="card title">
            {{ form.title|materializecss:'icon=create' }}
            {{ form.description|materializecss:'icon=subtitles' }}
            {{ form.students|materializecss:'icon=school'}}
        </div>
        <div class="card main">
            {{ form.available_formats|materializecss }}
        </div>
        <div class="card date">
            <i class="material-icons">access_alarms</i> {{ form.temp_deadline }}
        </div>
        <button type="submit" class="waves-effect waves-light btn">DODAJ</button>
    </form>
</div>

{%endblock content %}

HomeworkCentre/templates/homework_templates/add_rating.html
{% extends 'index.html' %}

{% load static %}

{% block title %}OCEŃ ODPOWIEDŹ {% endblock title %}
{% block css %}

{%load materializecss %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css"
    integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
<!-- <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}"> -->
{% endblock css %}

{% block javascript %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js"
    integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

<script>
    $(document).ready(function () {

        // Initialize materialize data picker

        $('select').formSelect();

    });
</script>

{% endblock javascript %}

{%block content %}
<style>
    .card {
        -webkit-border-bottom-right-radius: 85px;
        -moz-border-radius-bottomright: 85px;
        border-bottom-right-radius: 85px;
        padding-top: 10px;
    }

    .card.horizontal {
        -webkit-border-top-left-radius: 70px;
        -moz-border-radius-topleft: 70px;
        border-top-left-radius: 70px;

        -webkit-border-bottom-right-radius: 0px;
        -moz-border-radius-bottomright: 0px;
        border-bottom-right-radius: 0px;
    }

    .btn{
        width: 96%;
        border-bottom-right-radius: 70px;
    }
</style>
<div class="container ">
    <h1>OCEŃ ODPOWIEDŹ</h1>
    <div class="col s12 m7">
        <div class="card horizontal">
            <div class="card-stacked">
                <div class="card-content">
                    <p>{{solution_to_rate.homework}}</p>
                </div>
                <div class="card-action">
                    <p>Uczeń: {{solution_to_rate.student}}</p>
                    Odpowiedź:
                    <blockquote>
                        {{solution_to_rate.description|linebreaks}}
                    </blockquote>
                </div>
                {% if solution_to_rate.homework_file %}
                <div class="card-action">
                    <a href="{{solution_to_rate.homework_file.url}}" target="new">Załącznik</a>
                </div>
                {% endif %}

            </div>
        </div>
    </div>

    <div class="card">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.rating|materializecss:'icon=star'}}
            {{ form.feedback|materializecss:'icon=rate_review' }}
            <button type="submit" class="waves-effect green btn"><i class="material-icons ">check</i></button>
        </form>
    </div>
</div>
{%endblock content %}

HomeworkCentre/templates/homework_templates/add_solution.html
{% extends 'index.html' %}

{% load static %}

{% block title %}DODAJ ODPOWIEDZ{% endblock title %}
{% block css %}
{%load materializecss %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css"
    integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
{% endblock css %}

{% block javascript %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js"
    integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

{% endblock javascript %}

{%block content %}
<style>
    div.card.form {
        padding-top: 10px;
        padding-left: 10px;
        -webkit-border-bottom-right-radius: 85px;
        -moz-border-radius-bottomright: 85px;
        border-bottom-right-radius: 85px;
    }

    div.card {
        /* border: 1px grey solid; */
    }

    div.card.homework {
        -webkit-border-top-left-radius: 85px;
        -moz-border-radius-topleft: 85px;
        border-top-left-radius: 85px;
    }

    .btn {
        background-color: #01579b;
        width: 20%;
        
    }

    button[type="submit"] {
        width: 96%;
        border-bottom-right-radius: 70px;
        
    }

</style>
<div class="container ">

    <div class="row">
        <div class="col s12">
            <div class="card homework">
                <div class="card-content">
                    <span class="card-title">{{title}}</span>
                    <blockquote>
                        <p>{{desc}}</p>
                    </blockquote>
                </div>
                <div class="card-action">
                    {% for format in title.available_formats %}
                    <a class="blue-text">{{format}}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="card form">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|materializecss}}
            <!-- {{form.description|materializecss}}
        {{form.homework_file|materializecss}} -->
            <button type="submit" class="waves-effect green btn">DODAJ</button>
        </form>
    </div>
</div>
{%endblock content %}

HomeworkCentre/templates/homework_templates/rating.html
{% extends 'index.html' %}

{% load static %}

{% block title %}OCENA{% endblock title %}
{% block css %}
{%load materializecss %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css"
    integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
{% endblock css %}

{% block javascript %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js"
    integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

{% endblock javascript %}

{%block content %}
<style>
    div.card.form {
        padding-top: 10px;
        padding-left: 10px;
        -webkit-border-bottom-right-radius: 85px;
        -moz-border-radius-bottomright: 85px;
        border-bottom-right-radius: 85px;
    }

    div.card {
        /* border: 1px grey solid; */
    }

    div.card.homework {
        -webkit-border-top-left-radius: 85px;
        -moz-border-radius-topleft: 85px;
        border-top-left-radius: 85px;
    }

    .btn {
        background-color: #01579b;
        width: 20%;

    }

    button[type="submit"] {
        width: 96%;
        border-bottom-right-radius: 70px;

    }

    .container {
        margin-top: 20px;
    }
</style>
<div class="container">

    <div class="row">
        <div class="col s12">
            <div class="card homework">
                <div class="card-content">
                    <span class="card-title">{{rate.solution}}</span>
                  
                        <p>{{rate.solution.homework.description}}</p>
                   
                </div>
                <div class="card-action">
                    Twoja odpowiedź:
                    <blockquote>
                        {{rate.solution.description}}
                    </blockquote>
                </div>
                {% if rate.solution.homework_file %}
                <div class="card-action">
                    <a href="{{rate.solution.homework_file.url}}" class="blue-text" target="new">Załącznik</a>
                </div>
                {% endif %}
                <!-- <div class="card-action">
                    {% for format in title.available_formats %}
                    <a class="blue-text">{{format}}</a>
                    {% endfor %}
                </div> -->
            </div>
        </div>
    </div>

    <div class="card form">
      <div class="card-content">
          <p>Ocena: {{rate.rating}}</p>
          <p>Komentarz: <blockquote>{{rate.feedback}}</blockquote></p>
          <p>Wystawił/a: {{rate.rated_by}}</p>
      </div>
    </div>
</div>
{%endblock content %}

HomeworkCentre/templates/homework_templates/ratings.html
{% extends 'index.html' %}
{% block title %}OCENY{% endblock title %}

{% block content %}
siema
<table>
    {% for rating in rating_list %}
    <p>{{rating}}</p>
    {% endfor %}
</table>
{% endblock content %}

HomeworkCentre/templates/homework_templates/solutions.html
{% extends 'index.html' %}

{% load static %}

{% block title %}ODPOWIEDZI{% endblock title %}


{% block javascript %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js"
    integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $('.sidenav').sidenav();
    });
</script>

{% endblock javascript %}

{%block content %}
<style>
    .collection {
        border: 1px grey solid;
    }
    
</style>

<div class="container ">

    <h1>Rozwiązania</h1>
    <div class="row">
        {% regroup solution_list by homework as homework_groups %}

        {% for homework_group in homework_groups %}
        <div class="righ-align col s12">
            <ul class="collection with-header ">
                <li class="collection-header">
                    <h5>{{ homework_group.grouper }}
                        {% for class in homework_group.grouper.students.all %}
                        <span class="badge light-blue darken-4 white-text">{{class.name}}</span>
                        {% endfor %}
                    </h5>
                </li>
                {% for solution in homework_group.list|dictsort:"date_added" %}
                <li class="collection-item">
                    <div>{{solution.student}} {{solution.date_added|date:'d-m-Y H:i'}}<a
                            class="right btn-floating btn-small light-green darken-4 pulse"
                            href="{% url 'Homework:rating_create' solution.id %}"><i class="material-icons">edit</i></a>
                    </div>
                </li>
                {% endfor %}
                </li>
            </ul>
        </div>
        {% endfor%}
    </div>




</div>
{%endblock content %}

HomeworkCentre/templates/homework_templates/student_homeworks.html
{% extends 'index.html' %}

{% block title %}ZADANIA{% endblock title %}

{% block content %}
<style>
    .card.center {
        height: 250px;
    }
</style>

<div class="container">
    <h1 class="spadaj">Twoje zadania</h1>
    <div class="row">
        {% for homework in homework_list|dictsort:"deadline" %}
        <div class="col s6 m4">
            <div class="card center hoverable">
                <div class="card-image">
                    <i class="large material-icons">event_available</i>
                </div>
                <div class="card-content ">
                    <p>{{homework}}</p>
                    <cite>
                        <p class="truncate">{{homework.description}}</p>
                        <p>Termin: {{homework.deadline|date:'d-m-Y H:i'}}</p>
                    </cite>
                    <a class="btn-floating btn-medium waves-effect waves-light green pulse"
                        href="{% url 'homework:create_solution' homework.id %}"><i
                            class="material-icons">forward</i></a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

HomeworkCentre/templates/homework_templates/student_ratings.html
{% extends 'index.html' %}

{% block title %}OCENY{% endblock title %}

{% block javascript %}
<script>
    $(document).ready(function () {
        $('.modal').modal();
    });
</script>
{% endblock javascript %}
{% block content %}
    <style>
        a{
            text-decoration: none;
        }
    </style>
<div class="container">
    <table class="responsive-table highlight">
        <thead>
            <tr>
                <th>Zadanie</th>
                <th>Wystawił/a</th>
                <th>Data</th>
                <th>Ocena</th>
            </tr>
        </thead>

        <tbody>
            {% for rate in rating_list %}
            <tr>
                <td><a class="black-text" href="{{rate.id}}">{{rate.solution.homework}}</a></td>
                <td>{{rate.rated_by}}</td>
                <td>{{rate.date_added|date:'d-m-Y H:i'}}</td>
                <td>{{rate.rating}}</td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}

HomeworkCentre/templates/homework_templates/teacher_homeworks.html
{% extends 'index.html' %}

{% block title %}ZADANIA{% endblock title %}

{% block content %}

<div class="container">
    <table class="responsive-table highlight">
        <thead>
            <tr>
                <th>Nazwa</th>
                <th>Termin oddania</th>
                <th>Nadesłano</th>
                <th>Oceń</th>
                <th>Ocenione</th>
            </tr>
        </thead>

        <tbody>
            {% for homework in homework_list|dictsort:"title"|dictsortreversed:"deadline" %}
            <tr>
                <td>{{homework.title}}</td>
                <td>{{homework.deadline|date:'d-m-Y H:i'}}</td>
                <td>{{homework.homework.count}}</td>
                <td><a href="{% url 'homework:solutions_to_homework' homework.id %}"><i class="material-icons center green-text">create</i></a></td>
                <td><a href="{% url 'homework:ratings_to_homework' homework.id %}"><i class="material-icons center green-text">check</i></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}

HomeworkCentre/templates/homework_templates/teacher_ratings.html
{% extends 'index.html' %}

{% block title %}OCENY{% endblock title %}

{% block content %}

<div class="container">
    <table class="responsive-table highlight">
        <thead>
            <tr>
                <th>Zadanie</th>
                <th>Rozwiązanie</th>
                <th>Kto</th>
                <th>Ocena</th>
            </tr>
        </thead>

        <tbody>
            {% for rate in rating_list %}
            <tr>
                <td>{{rate.solution.homework}}</td>
                <td><a href="{% url 'homework:rating' rate.id %}"><i class="material-icons center green-text">library_books</i></a></td>
                <td>{{rate.solution.student}}</td>
                <td>{{rate.rating}}</td>
                
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}